//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Branch
{
    public int Id { get; set; }
    public string Name { get; set; }
    public Nullable<System.DateTime> Since { get; set; }
    public string Logo { get; set; }
}

public partial class BranchesMenu
{
    public int Id { get; set; }
    public Nullable<int> CategoryId { get; set; }
    public string Name { get; set; }
    public string Intro { get; set; }
    public Nullable<decimal> Price { get; set; }
    public string Code { get; set; }
    public Nullable<bool> IsActive { get; set; }
}

public partial class Category
{
    public int Id { get; set; }
    public Nullable<int> BranchId { get; set; }
    public string Name { get; set; }
    public Nullable<bool> IsActive { get; set; }
}

public partial class Order
{
    public int Id { get; set; }
    public Nullable<int> SourceUserId { get; set; }
    public Nullable<int> DestinationUserId { get; set; }
    public Nullable<int> MenuBranchId { get; set; }
    public Nullable<bool> IsApproved { get; set; }
}

public partial class Payment
{
    public int Id { get; set; }
    public Nullable<int> OrderId { get; set; }
    public Nullable<bool> IsPayment { get; set; }
}

public partial class Permission
{
    public int Id { get; set; }
    public string Permission1 { get; set; }
}

public partial class User
{
    public int Id { get; set; }
    public Nullable<int> BranchId { get; set; }
    public Nullable<int> UserTypeId { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public string Name { get; set; }
    public string Surname { get; set; }
    public string Phone { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public string Deneme { get; set; }
}

public partial class UserPermission
{
    public int Id { get; set; }
    public Nullable<int> UserId { get; set; }
    public Nullable<int> PermissionId { get; set; }
}

public partial class UserType
{
    public int Id { get; set; }
    public string Type { get; set; }
}
