//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bespoke.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> SourceUserId { get; set; }
        public Nullable<int> DestinationUserId { get; set; }
        public Nullable<int> MenuBranchId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    }
}
